# Generated by Django 4.2 on 2026-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.CharField(max_length=100)),
                ('coupon_code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.CharField(max_length=10)),
                ('min_order_amount', models.CharField(max_length=20)),
                ('max_discount_amount', models.CharField(max_length=20)),
                ('valid_from', models.CharField(max_length=25)),
                ('valid_to', models.CharField(max_length=25)),
                ('usage_limit', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('delivery_person', models.CharField(max_length=100)),
                ('pickup_time', models.CharField(max_length=25)),
                ('delivery_time', models.CharField(max_length=25)),
                ('estimated_time', models.CharField(max_length=20)),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_fee', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.CharField(max_length=100)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('quantity_available', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('reorder_level', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(max_length=100)),
                ('last_restocked_date', models.CharField(max_length=25)),
                ('cost_per_unit', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('kitchen_name', models.CharField(max_length=100)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('operating_hours', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=20)),
                ('logo', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='menucategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('display_order', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('discount_price', models.CharField(max_length=20)),
                ('preparation_time', models.CharField(max_length=20)),
                ('veg_non_veg', models.CharField(max_length=10)),
                ('spice_level', models.CharField(max_length=10)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('availability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_date', models.CharField(max_length=25)),
                ('read_status', models.CharField(max_length=10)),
                ('notification_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('kitchen', models.CharField(max_length=100)),
                ('order_date', models.CharField(max_length=25)),
                ('delivery_address', models.CharField(max_length=200)),
                ('total_amount', models.CharField(max_length=20)),
                ('discount_applied', models.CharField(max_length=20)),
                ('final_amount', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=20)),
                ('special_instructions', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('menu_item', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=5)),
                ('unit_price', models.CharField(max_length=20)),
                ('total_price', models.CharField(max_length=20)),
                ('customization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=30)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('kitchen', models.CharField(max_length=100)),
                ('menu_item', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=5)),
                ('review_text', models.TextField()),
                ('review_date', models.CharField(max_length=25)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
