# Generated by Django 4.2.27 on 2026-05-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='kitchen',
            new_name='menuitem',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='operating_hours',
        ),
    ]
