# Generated by Django 4.2 on 2026-05-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer",
            "0002_rename_kitchen_menuitem_menuitem_remove_kitchen_logo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchen",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
